using System.Collections.Generic;

namespace WixXmlGenerator.Commands
{
    public class HelpCommand : Command, ICommand
    {
        private readonly string _helpString;

        public HelpCommand():base(0)
        {
            _helpString += "Wix XML Generator has 3 commands:\n";
            _helpString += "-help: Displays the help text.\n";
            _helpString += "-version: Displays the version information.\n";
            _helpString += "-generate: Generates the XML based on the arguments.\n";
            _helpString += "\n";
            _helpString += "Generate command arguments are:\n";
            _helpString += "-sourceDir: This is the root folder where the tool will build the folders, files and components from.\n";
            _helpString += "-wxsPath: This is the file path of the Product.wxs.\n";
            _helpString += "projectName: This is the `INSTALLDIR` of the setup.\n";
            _helpString += "-outputFile: This file contains the XML that is generated by the tool. While the file will have XML formatted text, there is no restriction on the file extension. It can be anything.\n";
            _helpString += "\n";
            _helpString += "The basic usage of the tool is as follows:\n";
            _helpString += "WixXmlGenerator.exe - generate - sourceDir <SOURCE_DIRECTORY_PATH> -wxsPath <WXS_FILE_PATH> -projectName <PROJECT_NAME> -outputFile <OUTPUT_FILE_PATH>\n";
        }

        public string Execute(List<string> args)
        {
            return _helpString;
        }
    }
}
